baseURL = 'https://xuanxue.club/'
languageCode = 'zh-cn'
title = '玄学社'
theme='hugo-theme-stack'

[permalinks]
page = "/:slug/"
post = "/:slug/"

[params]
favicon = "/favicon.ico"

[params.article]
math = true
readingTime = false
toc = true

[params.sidebar]
subtitle = "玄之又玄，众妙之门"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/xuan.png"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "categories"

[[params.widgets.homepage]]
type = "tag-cloud"

[[params.widgets.page]]
type = "toc"

[[menu.main]]
identifier = "home"
name = "主页"
url = "/"
weight = -100

[menu.main.params]
icon = "home"
newTab = false

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search"
weight = -60

[menu.main.params]
icon = "search"
newTab = false

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/AIImmortal/XuanXueClub"

[menu.social.params]
icon = "brand-github"

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200